import esbuild from "esbuild";
import {copyFile, mkdir, stat} from "node:fs/promises";
import {builtinModules} from "node:module";
import path from "node:path";
import process from "node:process";
import {fileURLToPath} from "node:url";

const pluginId = "draw-in-canvas";
const projectRoot = path.dirname(fileURLToPath(import.meta.url));
const defaultTestingVault = "/mnt/d/plugin-testing-vault";
const testingVault = resolveVaultPath(process.env.OBSIDIAN_TEST_VAULT ?? defaultTestingVault);
const testingPluginDir = path.join(testingVault, ".obsidian", "plugins", pluginId);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv.includes("production");

const copyToTestingVaultPlugin = {
	name: "copy-to-testing-vault",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) {
				return;
			}

			try {
				await copyReleaseFilesToTestingVault();
			} catch (error) {
				console.error(error);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: prod ? [] : [copyToTestingVaultPlugin],
});

if (prod) {
	await context.rebuild();
	await context.dispose();
	await copyReleaseFilesToTestingVault();
	process.exit(0);
}

await context.watch();
console.log(`Watching ${pluginId}; rebuilds copy to ${testingPluginDir}`);

async function copyReleaseFilesToTestingVault() {
	const obsidianDir = path.join(testingVault, ".obsidian");

	if (!(await directoryExists(obsidianDir))) {
		console.warn(`Skipping testing-vault copy: expected ${obsidianDir} to exist.`);
		return;
	}

	await mkdir(testingPluginDir, {recursive: true});
	await Promise.all(["main.js", "manifest.json", "styles.css"].map((fileName) => copyFile(
		path.join(projectRoot, fileName),
		path.join(testingPluginDir, fileName),
	)));
	console.log(`Copied plugin files to ${testingPluginDir}`);
}

async function directoryExists(dir) {
	try {
		return (await stat(dir)).isDirectory();
	} catch {
		return false;
	}
}

function resolveVaultPath(rawPath) {
	const windowsPathMatch = /^([A-Za-z]):[\\/](.*)$/.exec(rawPath.trim());

	if (!windowsPathMatch) {
		return rawPath;
	}

	const drive = windowsPathMatch[1].toLowerCase();
	const rest = windowsPathMatch[2].replace(/\\/g, "/");
	return `/mnt/${drive}/${rest}`;
}
